### ISSUE TITLE
Changing Working Directory Causes Mosek to Not Run

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#233]
Another dumb question for @bqpd...

I'm trying to run the following:

``` python
import gpkit

# Decision variables
x = gpkit.Variable('x')
y = gpkit.Variable('y')

# must enable signomials for subtraction
gpkit.enable_signomials()

# create and solve the SP
sp = gpkit.SP(x, [x >= 1-y, y <= 0.1])
sol = sp.localsolve(printing=False)
assert abs(sol(x) - 0.9) < 1e-6

gpkit.disable_signomials()
```

and getting the following:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-25-927fd86550b3> in <module>()
     10 # create and solve the SP
     11 sp = gpkit.SP(x, [x >= 1-y, y <= 0.1])
---> 12 sol = sp.localsolve(printing=False)
     13 assert abs(sol(x) - 0.9) < 1e-6
     14 

/Users/codykarcher/anaconda/lib/python2.7/site-packages/gpkit/signomial_program.pyc in localsolve(self, printing, xk, reltol, *args, **kwargs)
    148         self.presolve = self.last
    149 
--> 150         sol = self._solve(printing=printing, *args, **kwargs)
    151         if printing:
    152             print "Solving took %i GP solves." % self.sp_iters

/Users/codykarcher/anaconda/lib/python2.7/site-packages/gpkit/geometric_program.pyc in _solve(self, solver, printing, skipfailures, allownonoptimal)
    359             solverfn = cli_expopt.imize_fn(filename)
    360         elif solver == "mosek":
--> 361             from ._mosek import expopt
    362             solverfn = expopt.imize
    363         elif hasattr(solver, "__call__"):

/Users/codykarcher/anaconda/lib/python2.7/site-packages/gpkit/_mosek/expopt.py in <module>()
     33     from lib import expopt_h
     34 except Exception as e:
---> 35     raise ImportError("Could not load MOSEK library: "+repr(e))
     36 
     37 

ImportError: Could not load MOSEK library: ImportError(OSError('dlopen(/Users/codykarcher/.gpkit/expopt.so, 10): Library not loaded: @loader_path/libmosek64.7.0.dylib\n  Referenced from: /Users/codykarcher/.gpkit/expopt.so\n  Reason: image not found',),)
```

This is because I'm trying to work in a folder that isn't `gpkit`.  I remember we had this issue before, but @bqpd just fixed it for me and I don't know how to do it again.  I figured this may be a recurring issue and it would be nice to have it documented here.

**Comment by bqpd** [comment]
Hmm, I don't think that's why. What's `cat ~/.bash_profile` look like?

**Comment by cjk12** [comment]
I have no idea if this is what you want:
```
# added by Anaconda 2.1.0 installer
export PATH="/Users/codykarcher/anaconda/bin:$PATH"
```
The above comment is from an ipython notebook, so this is what I get when I type `cat ~/.bash_profile` into the terminal in the same working directory.

**Comment by bqpd** [comment]
Ah, there's your problem. After pulling, you need to run the new build
script, I think. Try `python build.py` in the gpkit directory?

**Comment by cjk12** [comment]
It didn't like that...  Here is my terminal session:

```
Codys-MacBook-Pro:gpkit codykarcher$ python build.py
python: can't open file 'build.py': [Errno 2] No such file or directory
Codys-MacBook-Pro:gpkit codykarcher$ ls
LICENSE		MANIFEST	README.md	docs		gpkit		setup.py
Codys-MacBook-Pro:gpkit codykarcher$ 
```

**Comment by cjk12** [comment]
Went one level down and it worked.  Standby.

**Comment by cjk12** [comment]
New `cat ~/.bash_profile`

```
# added by Anaconda 2.1.0 installer
export PATH="/Users/codykarcher/anaconda/bin:$PATH"

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Users/codykarcher/mosek/7/tools/platform/osx64x86/bin
```

**Comment by bqpd** [comment]
Should work now.

**Comment by cjk12** [comment]
Did you do something?  My pull is saying I'm up to date.

**Comment by bqpd** [comment]
Naw, but that line in your bash_profile should cause MOSEK to work. You may
have to run gpkit in a new terminal window for this to take effect.

**Comment by cjk12** [comment]
It's definitely still doing the same thing I originally posted...  Did a new window, recycled all the ipython notebooks, tried pulling again...  Still not working.

**Comment by bqpd** [comment]
Darn. Just to check, you started iPython in that new window?

**Comment by cjk12** [comment]
Yea, completely cycled all things python related.  I have enough to do until Thursday, but if we can figure it out then, that would be great.

**Comment by bqpd** [comment]
Sure thing.

**Comment by cjk12** [comment]
I did something dumb.  It's fixed now.

**Comment by bqpd** [comment]
It'd be great to figure out what went wrong, for future purposes!
